schema_version: 1

context:
  name: terminaltexteffects
  version: "0.14.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/terminaltexteffects-${{ version }}.tar.gz
  sha256: b27e6ea840595728940a3e258469c4c192c589bfa6d02ad2b4f8a89c58cccfa1

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - tte = terminaltexteffects.__main__:main
      - terminaltexteffects = terminaltexteffects.__main__:main

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - terminaltexteffects
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - python ${{ python_min }}
    script:
      - tte --help
      - terminaltexteffects --help

about:
  summary: TerminalTextEffects (TTE) is a terminal visual effects engine.
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/ChrisBuilds/terminaltexteffects
  documentation: https://chrisbuilds.github.io/terminaltexteffects/

extra:
  recipe-maintainers:
    - thewchan
